### ISSUE TITLE
MCQ4structures installation dependency issue

### ISSUE THREAD

**Issue by mandar5335** [tzok/mcq4structures#4]
Dear Tomasz,

I am trying to install MCQ4structures by cloning mcq-parent, however, I am facing the following error:

`Failed to execute goal on project circular: Could not resolve dependencies for project pl.poznan.put:circular:jar:1.3.2: Failure to find pl.poznan.put:TzokCommons:jar:1.5.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]`

I am not sure about the origin of this error. My Java version is 1.8.0_311. Could this be a problem?

Looking forward to your reply.

Best Regards,
Mandar Kulkarni

**Comment by tzok** [comment]
Dear @mandar5335 

I will have a look at that issue. In the meantime, can you try to use the released version 1.6?

https://github.com/tzok/mcq4structures/releases

**Comment by mandar5335** [comment]
Hi,
Thanks for your reply. `mcq-cli-1.6.tar.gz `version is working perfectly. 

Best,
Mandar Kulkarni

**Comment by tzok** [comment]
Fixed in 1.7.0
